app:
    path: /
    defaults: { _controller: AppBundle:Default:index }

link:
    path:   /link
    defaults: { _controller: AppBundle:Link:index }

add_link:
    path: /link/add
    defaults: { _controller: AppBundle:Link:add}