app:
    path: /
    defaults: { _controller: AppBundle:Default:index }

link:
    path:   /link
    defaults: { _controller: AppBundle:Link:index }

add_link:
    path: /link/add
    defaults: { _controller: AppBundle:Link:add}

folder:
    path: /category/{category}
    defaults: {_controller: AppBundle:Folder:index}

add_folder:
    path: /folder/add
    defaults: {_controller: AppBundle:Folder:add}